# Pricing information per provider and model - 2025 Latest Models (per 1M tokens)
pricing:
  openai:
    gpt-5:
      input_cost_per_1m: 3.00
      output_cost_per_1m: 15.00
      request_cost: 0
    o3:
      input_cost_per_1m: 5.00
      output_cost_per_1m: 20.00
      request_cost: 0
    o4-mini:
      input_cost_per_1m: 1.00
      output_cost_per_1m: 5.00
      request_cost: 0

  anthropic:
    claude-opus-4.1:
      input_cost_per_1m: 15.00
      output_cost_per_1m: 75.00
      request_cost: 0
    claude-sonnet-4:
      input_cost_per_1m: 3.00
      output_cost_per_1m: 15.00
      request_cost: 0

  google:
    gemini-2.5-pro:
      input_cost_per_1m: 3.50
      output_cost_per_1m: 10.50
      request_cost: 0
    gemini-2.5-flash:
      input_cost_per_1m: 0.075
      output_cost_per_1m: 0.30
      request_cost: 0

  xai:
    grok-4:
      input_cost_per_1m: 3.00
      output_cost_per_1m: 15.00
      request_cost: 0
    grok-4-heavy:
      input_cost_per_1m: 5.00
      output_cost_per_1m: 25.00
      request_cost: 0